# @package _global_
defaults:
  - /trainer: default
  - /loader: default
  - /dataset: codon_scoring
  - /task: binary_classification
  - /optimizer: adamw
  - /scheduler: plateau
  - /callbacks: [base, classification_csv_logging]

train:
  monitor:
  mode: max

encoder: id

# we need this for classification!
decoder:
  _name_: sequence
  mode: pool
