# @package _global_
defaults:
  - /trainer: default
  - /loader: default
  - /dataset: synapse_regression
  - /task: regression
  - /optimizer: adamw
  - /scheduler: plateau
  - /callbacks: [base, checkpoint, regression_csv_logging]

train:
  monitor: val/accuracy # Needed for plateau scheduler
  mode: max

encoder: id

# we need this for classification!
decoder:
  _name_: sequence
  mode: pool
