_name_: synapse_regression
dataset_name: synapse_regression
csv_path:
train_fasta_path:
validation_fasta_path:
test_fasta_path:
predict_fasta_path:
synapse_label_name:
upsample: True
max_length: 1024
d_output: 1
batch_size: 8  # per GPU
batch_size_eval: ${.batch_size}
num_workers: 4  # For preprocessing only
add_eos: False
__l_max: ${.max_length}
shuffle: true  # set this as default!
